<a href="https://colab.research.google.com/github/x-nbriones/Briones-CS3B_CSST101/blob/main/Exer3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Course Enrollment**

1. Create the Database

In [10]:
students <- data.frame(
  Student_ID= c("S001", "S002", "S003", "S004", "S005", "S006", "S007", "S008"),
  Programming_Grade= c(88,72,91,78,65,85,74,82),
  Math_Grade= c(85,70,88,80,68,90,73,79),
  Attendance= c(92,80,95,88,70,91,76,85),
  Prerequisite= c("Yes", "No", "Yes", "Yes", "No", "Yes", "No", "Yes")
)
students

  Student_ID Programming_Grade Math_Grade Attendance Prerequisite
1 S001       88                85         92         Yes
2 S002       72                70         80         No
3 S003       91                88         95         Yes
4 S004       78                80         88         Yes
5 S005       65                68         70         No
6 S006       85                90         91         Yes
7 S007       74                73         76         No
8 S008       82                79         85         Yes

2. Explore the data

In [11]:
summary(students)
nrow(students)
ncol(students)

cat("\n")

max(students$Programming_Grade)
max(students$Math_Grade)
max(students$Attendance)
max(students$Prerequisite)

cat("\n")

min(students$Prerequisite)

cat("\n")
sum(students$Programming_Grade)
cat("\n")
mean(students$Math_Grade)
cat("\n")
ave(students$Attendance)

     Student_ID Programming_Grade   Math_Grade      Attendance
 Length   :8    Min.   :65.00     Min.   :68.00   Min.   :70.00
 N.unique :8    1st Qu.:73.50     1st Qu.:72.25   1st Qu.:79.00
 N.blank  :0    Median :80.00     Median :79.50   Median :86.50
 Min.nchar:4    Mean   :79.38     Mean   :79.12   Mean   :84.62
 Max.nchar:4    3rd Qu.:85.75     3rd Qu.:85.75   3rd Qu.:91.25
                Max.   :91.00     Max.   :90.00   Max.   :95.00
    Prerequisite
 Length   :8
 N.unique :2
 N.blank  :0
 Min.nchar:2
 Max.nchar:3

[1] 8

[1] 5

[1] 91

[1] 90

[1] 95

[1] "Yes"

[1] "No"

[1] 635

[1] 79.125

[1] 84.625 84.625 84.625 84.625 84.625 84.625 84.625 84.625

3. Enter a Student ID

In [12]:
student_id <- readline("Enter Student ID: ")
print(student_id)

Enter Student ID: S005
[1] "S005"

4. Search the data frame

In [13]:
student <- students[
  students$Student_ID == student_id,
]
student

  Student_ID Programming_Grade Math_Grade Attendance Prerequisite
5 S005       65                68         70         No

5. Check if the student exists

In [14]:
if (nrow(student) > 0) {
  print("Found")
  student
} else {
  print("Not found")
}

[1] "Found"

  Student_ID Programming_Grade Math_Grade Attendance Prerequisite
5 S005       65                68         70         No

6. Extract student information

In [15]:
programming = student$Programming_Grade
math = student$Math_Grade
prereq = student$Prerequisite
attendance = student$Attendance

cat("Programming Grade: ", programming)
cat("\nMath Grade: ", math)
cat("\nAttendance: ", attendance)
cat("\nPrerequisite: ", prereq)

Programming Grade:  65
Math Grade:  68
Attendance:  70
Prerequisite:  No

7. Implement Rules

**Rule 1** - Eligible: Programming Grade >= 80 AND Math Grade >= 75 AND Attendance >= 80% AND

Prerequisite = Yes.

**Rule 2**- Conditionally Eligible: Programming Grade >= 75 AND Math Grade >= 70 AND Attendance>= 75%, but Rule 1 is not satisfied.

**Rule 3** - Not Eligible: If neither Rule 1 nor Rule 2 is satisfied, classify the student as Not Eligible.

In [16]:
if (programming >= 80 && math >= 75 && attendance >= 80 && prereq == "Yes") {
 condition <- "Eligible"
} else if (programming >= 75 && math >= 70 && attendance >= 75) {
 condition <- "Conditionally Eligible"
} else {
 condition <- "Not Eligible"
}


cat("Student Classification: ", condition)

Student Classification:  Not Eligible

8. Apply the function to all students

In [25]:
classify_student <- function(student_row) {
  programming <- student_row['Programming_Grade']
  math <- student_row['Math_Grade']
  attendance <- student_row['Attendance']
  prereq <- student_row['Prerequisite']

  if (programming >= 80 && math >= 75 && attendance >= 80 && prereq == "Yes") {
    return("Eligible")
  } else if (programming >= 75 && math >= 70 && attendance >= 75) {
    return("Conditionally Eligible")
  } else {
    return("Not Eligible")
  }
}

students$Classification <- apply(students, 1, classify_student)
students

  Student_ID Programming_Grade Math_Grade Attendance Prerequisite
1 S001       88                85         92         Yes
2 S002       72                70         80         No
3 S003       91                88         95         Yes
4 S004       78                80         88         Yes
5 S005       65                68         70         No
6 S006       85                90         91         Yes
7 S007       74                73         76         No
8 S008       82                79         85         Yes
  Classification
1 Eligible
2 Not Eligible
3 Eligible
4 Conditionally Eligible
5 Not Eligible
6 Eligible
7 Not Eligible
8 Eligible

9. Create recommendation rules

In [26]:
recommend_student <- function(classification_status) {
  if (classification_status == "Eligible") {
    return("Student may enroll")
  } else if (classification_status == "Conditionally Eligible") {
    return("Consult Academic adviser")
  } else {
    return("Complete requirements before enrollment")
  }
}

students$Recommendation <- sapply(students$Classification, recommend_student)
students

  Student_ID Programming_Grade Math_Grade Attendance Prerequisite
1 S001       88                85         92         Yes
2 S002       72                70         80         No
3 S003       91                88         95         Yes
4 S004       78                80         88         Yes
5 S005       65                68         70         No
6 S006       85                90         91         Yes
7 S007       74                73         76         No
8 S008       82                79         85         Yes
  Classification         Recommendation
1 Eligible               Student may enroll
2 Not Eligible           Complete requirements before enrollment
3 Eligible               Student may enroll
4 Conditionally Eligible Consult Academic adviser
5 Not Eligible           Complete requirements before enrollment
6 Eligible               Student may enroll
7 Not Eligible           Complete requirements before enrollment
8 Eligible               Student may enroll

In [39]:
cat("\n==========================================\n")
  cat("       COURSE ENROLLMENT ADVISER\n")
  cat("==========================================\n\n")

  cat("Student ID:", student$Student_ID, "\n\n")

  cat("Programming Grade:", programming, "\n")
  cat("Math Grade:", math, "\n")
  cat("Attendance:", attendance, "\n")
  cat("Prerequisite:", prereq, "\n\n")

  cat("Enrollment Status:\n")
  cat(student$Classification, "\n\n")

  cat("Recommendation:\n")
  cat(student$Recommendation, "\n\n")

  cat("==========================================\n")

==========================================
       COURSE ENROLLMENT ADVISER
==========================================

Student ID: S005

Programming Grade: 65
Math Grade: 68
Attendance: 70
Prerequisite: No

Enrollment Status:
Not Eligible

Recommendation:
Complete requirements before enrollment

==========================================